name: Sync External README
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行（可自定义）
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v4

      - name: 下载他人 README.md
        run: |
          wget -O external-readme.md https://raw.githubusercontent.com/<目标用户名>/<目标仓库>/<分支>/README.md

      - name: 提取指定行代码
        run: |
          # 示例：提取第 10 行（行号从 1 开始）
          sed -n '10p' external-readme.md > extracted-line.txt

      - name: 更新自己的 README.md
        run: |
          # 替换标记行（需预先在 README.md 中添加 <!-- AUTO-SYNC-LINE -->）
          sed -i "/<!-- AUTO-SYNC-LINE -->/c $(cat extracted-line.txt)\n<!-- AUTO-SYNC-LINE -->" README.md

      - name: 提交更改
        uses: EndBug/add-and-commit@v9
        with:
          message: "自动同步 README 代码行"
          add: README.md
