name: Sync First Line of README

on:
  schedule:
    # 每天 UTC 时间 00:00 自动运行（北京时间 08:00）
    - cron: "5 * * * *"
  workflow_dispatch:  # 可选：允许手动触发

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出你的仓库（需写入权限）
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}  # 需配置有写入权限的 Token

      # 2. 下载对方的 README.md
      - name: Fetch target README
        run: |
          # 公开仓库直接下载
          curl -s -o external-readme.md https://raw.githubusercontent.com/目标用户/目标仓库/main/README.md

          # 如果是私有仓库，需添加 Token 授权
          # curl -H "Authorization: token ${{ secrets.ACTION_TOKEN }}" -o external-readme.md https://github.com/toshare5/toshare5.github.io/blob/main/README.md

      # 3. 提取目标行并转义特殊字符
      - name: Extract line
        run: |
          # 提取第 N 行（例如第 29 行）
          TARGET_LINE=$(sed -n '29p' external-readme.md)

          # 转义特殊字符（避免 sed 报错）
          ESCAPED_LINE=$(echo "$TARGET_LINE" | sed 's/[\/&]/\\&/g; s/"/\\"/g')

          # 保存到环境变量
          echo "SYNCED_CONTENT=$ESCAPED_LINE" >> $GITHUB_ENV

      # 4. 覆盖你的 README 第一行
      - name: Override first line
        run: |
          sed -i "1s|^.*$|${{ env.SYNCED_CONTENT }}|" README.md

      # 5. 提交并推送更改
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "自动同步 README 第一行"
          add: README.md
