name: Force Sync README First Line

on:
  schedule:
    # 每天 UTC 0 点自动执行（北京时间 8 点，可修改 cron 表达式）
    - cron: "0 0 * * *"
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-first-line:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出你的仓库（需写入权限）
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}  # 需配置有写入权限的 Token

      # 2. 下载对方的 README.md
      - name: Fetch target README
        run: |
          # 公开仓库直接下载（私有仓库需替换为带 Token 的 URL）
          curl -s -o external.md https://github.com/toshare5/toshare5.github.io/blob/main/README.md

      # 3. 强制提取目标行（行号可调）
      - name: Extract line
        id: extract
        run: |
          # 提取第 N 行（例如第 5 行）
          TARGET_LINE=$(sed -n '29p' external.md)

          # 如果目标行不存在，终止流程
          if [ -z "$TARGET_LINE" ]; then
            echo "错误：目标行不存在"
            exit 1
          fi

          # 转义特殊字符（/ & "）
          ESCAPED_LINE=$(echo "$TARGET_LINE" | sed -e 's/[\/&]/\\&/g' -e 's/"/\\"/g')
          echo "SYNCED_CONTENT=$ESCAPED_LINE" >> $GITHUB_ENV

      # 4. 强制覆盖第一行
      - name: Override first line
        run: |
          # 使用管道强制替换（兼容空行）
          echo "${{ env.SYNCED_CONTENT }}" > temp.md
          tail -n +2 README.md >> temp.md
          mv temp.md README.md

      # 5. 提交并强制推送
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "强制同步第一行内容"
          add: README.md
          force: true  # 强制覆盖历史记录（可选）
