jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to repo
        env:
          TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push https://$TOKEN@github.com/$REPO.git
